image: node:latest

services:
  - mysql:latest

before_script:
  - npm install
  - node_modules/.bin/sequelize db:migrate && NODE_ENV=test node_modules/.bin/sequelize db:migrate

test:
  script:
    - npm test
