image: node:latest

services:
  - mysql:latest

connect:
  image: mysql
  script:
    - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

variables:
  NODE_ENV: test
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: eca_test
  MYSQL_USER: eca_admin
  MYSQL_PASSWORD: password

cache:
  paths:
  - node_modules/

test:
  script:
    - npm install
    - NODE_ENV=test node_modules/.bin/sequelize db:migrate
    - npm test
