image: node:latest

services:
  - mysql:latest

variables:
  NODE_ENV: test
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: eca_test
  MYSQL_USER: eca_admin
  MYSQL_PASSWORD: password

cache:
  paths:
  - node_modules/

test:
  script:
    - npm install
    - node_modules/.bin/sequelize db:migrate
    - npm test
    - npm coverage
  artifacts:
    paths:
      - node_modules/
  coverage: Statements.*?(\d+(?:\.\d+)?)%
