image: node:latest

services:
  - mysql:latest

variables:
  - MYSQL_ROOT_PASSWORD: password
  - MYSQL_DATABASE: eca_test
  - MYSQL_USER: eca_admin
  - MYSQL_PASSWORD: password

cache:
  paths:
  - node_modules/

before_script:
  - npm install
  - node_modules/.bin/sequelize db:migrate && NODE_ENV=test node_modules/.bin/sequelize db:migrate

test:
  script:
    - npm test
